"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
BCA API"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DVBStandard:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DVBStandardEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DVBStandard.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DVB_STD_NONE: _DVBStandard.ValueType  # 0
    DVB_STD_DVB_S1: _DVBStandard.ValueType  # 1
    DVB_STD_DVB_S2: _DVBStandard.ValueType  # 2
    DVB_STD_DSS: _DVBStandard.ValueType  # 3
    DVB_STD_TURBO: _DVBStandard.ValueType  # 4
    DVB_STD_DVB_S2X: _DVBStandard.ValueType  # 5
    DVB_STD_UNKNOWN: _DVBStandard.ValueType  # 6

class DVBStandard(_DVBStandard, metaclass=_DVBStandardEnumTypeWrapper): ...

DVB_STD_NONE: DVBStandard.ValueType  # 0
DVB_STD_DVB_S1: DVBStandard.ValueType  # 1
DVB_STD_DVB_S2: DVBStandard.ValueType  # 2
DVB_STD_DSS: DVBStandard.ValueType  # 3
DVB_STD_TURBO: DVBStandard.ValueType  # 4
DVB_STD_DVB_S2X: DVBStandard.ValueType  # 5
DVB_STD_UNKNOWN: DVBStandard.ValueType  # 6
global___DVBStandard = DVBStandard

class _RollOffType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RollOffTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RollOffType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RT_ERROR: _RollOffType.ValueType  # 0
    RT_35: _RollOffType.ValueType  # 1
    RT_25: _RollOffType.ValueType  # 2
    RT_20: _RollOffType.ValueType  # 3
    RT_15: _RollOffType.ValueType  # 4
    RT_10: _RollOffType.ValueType  # 5
    RT_05: _RollOffType.ValueType  # 6
    RT_AUTO: _RollOffType.ValueType  # 9

class RollOffType(_RollOffType, metaclass=_RollOffTypeEnumTypeWrapper):
    """carrier type"""

RT_ERROR: RollOffType.ValueType  # 0
RT_35: RollOffType.ValueType  # 1
RT_25: RollOffType.ValueType  # 2
RT_20: RollOffType.ValueType  # 3
RT_15: RollOffType.ValueType  # 4
RT_10: RollOffType.ValueType  # 5
RT_05: RollOffType.ValueType  # 6
RT_AUTO: RollOffType.ValueType  # 9
global___RollOffType = RollOffType

class _Pilot:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PilotEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Pilot.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PT_ERROR: _Pilot.ValueType  # 0
    PT_OFF: _Pilot.ValueType  # 1
    PT_ON: _Pilot.ValueType  # 2

class Pilot(_Pilot, metaclass=_PilotEnumTypeWrapper):
    """According to ETSI EN 302 307 V1.3.1 (2013-03), see 5.5.2.3"""

PT_ERROR: Pilot.ValueType  # 0
PT_OFF: Pilot.ValueType  # 1
PT_ON: Pilot.ValueType  # 2
global___Pilot = Pilot

class _SpectralInversion:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpectralInversionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpectralInversion.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SI_NONE: _SpectralInversion.ValueType  # 0
    SI_ON: _SpectralInversion.ValueType  # 1
    SI_OFF: _SpectralInversion.ValueType  # 2
    SI_AUTO: _SpectralInversion.ValueType  # 3

class SpectralInversion(_SpectralInversion, metaclass=_SpectralInversionEnumTypeWrapper): ...

SI_NONE: SpectralInversion.ValueType  # 0
SI_ON: SpectralInversion.ValueType  # 1
SI_OFF: SpectralInversion.ValueType  # 2
SI_AUTO: SpectralInversion.ValueType  # 3
global___SpectralInversion = SpectralInversion

class _BoardStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BoardStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BoardStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BOARD_OK: _BoardStatus.ValueType  # 0
    BOARD_ERROR: _BoardStatus.ValueType  # 1

class BoardStatus(_BoardStatus, metaclass=_BoardStatusEnumTypeWrapper): ...

BOARD_OK: BoardStatus.ValueType  # 0
BOARD_ERROR: BoardStatus.ValueType  # 1
global___BoardStatus = BoardStatus

class _BitStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BitStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BitStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BS_PERFECT: _BitStatus.ValueType  # 0
    BS_E_COMM: _BitStatus.ValueType  # 1
    BS_E_OXFORD: _BitStatus.ValueType  # 2
    BS_E_TEMPSENSOR: _BitStatus.ValueType  # 4
    BS_E_FPGA: _BitStatus.ValueType  # 8
    BS_E_ERROR: _BitStatus.ValueType  # 1073741824
    """!< last one, do not go into sign bit"""

class BitStatus(_BitStatus, metaclass=_BitStatusEnumTypeWrapper): ...

BS_PERFECT: BitStatus.ValueType  # 0
BS_E_COMM: BitStatus.ValueType  # 1
BS_E_OXFORD: BitStatus.ValueType  # 2
BS_E_TEMPSENSOR: BitStatus.ValueType  # 4
BS_E_FPGA: BitStatus.ValueType  # 8
BS_E_ERROR: BitStatus.ValueType  # 1073741824
"""!< last one, do not go into sign bit"""
global___BitStatus = BitStatus

class _CommunicationStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CommunicationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CommunicationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CS_NONE: _CommunicationStatus.ValueType  # 0
    CS_CONNECTED: _CommunicationStatus.ValueType  # 1
    CS_NOT_FOUND: _CommunicationStatus.ValueType  # 2
    CS_ERROR: _CommunicationStatus.ValueType  # 3

class CommunicationStatus(_CommunicationStatus, metaclass=_CommunicationStatusEnumTypeWrapper): ...

CS_NONE: CommunicationStatus.ValueType  # 0
CS_CONNECTED: CommunicationStatus.ValueType  # 1
CS_NOT_FOUND: CommunicationStatus.ValueType  # 2
CS_ERROR: CommunicationStatus.ValueType  # 3
global___CommunicationStatus = CommunicationStatus

class _LockStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LockStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LockStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ZERO_PLACEHOLDER: _LockStatus.ValueType  # 0
    LOCK_DEFINITIF: _LockStatus.ValueType  # 1
    TUN_LOCKED: _LockStatus.ValueType  # 2
    PKTDELIN_LOCK: _LockStatus.ValueType  # 4
    LOCKEDVIT: _LockStatus.ValueType  # 8
    AGCRF_LOCKED: _LockStatus.ValueType  # 16
    PLL_LOCK: _LockStatus.ValueType  # 32
    CAR_LOCK: _LockStatus.ValueType  # 64
    TIMING_IS_LOCKED: _LockStatus.ValueType  # 128

class LockStatus(_LockStatus, metaclass=_LockStatusEnumTypeWrapper): ...

ZERO_PLACEHOLDER: LockStatus.ValueType  # 0
LOCK_DEFINITIF: LockStatus.ValueType  # 1
TUN_LOCKED: LockStatus.ValueType  # 2
PKTDELIN_LOCK: LockStatus.ValueType  # 4
LOCKEDVIT: LockStatus.ValueType  # 8
AGCRF_LOCKED: LockStatus.ValueType  # 16
PLL_LOCK: LockStatus.ValueType  # 32
CAR_LOCK: LockStatus.ValueType  # 64
TIMING_IS_LOCKED: LockStatus.ValueType  # 128
global___LockStatus = LockStatus

class _Modcod:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModcodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Modcod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FE_SAT_DUMMY_PLF: _Modcod.ValueType  # 0
    """
    0x00..1F: Legacy list; DVBS2
    0x20..3F: DVBS1
    0x40..7F: DVBS2-X With:  _S: Short frame (only here to make it work compile; otherwise there will be a redefinition of enumerator)
    _L: Linear constellation;
    _R_xx: reserved + Modcode number hex   Pon; Poff Pilots configuration
    """
    FE_SAT_QPSK_14: _Modcod.ValueType  # 1
    FE_SAT_QPSK_13: _Modcod.ValueType  # 2
    FE_SAT_QPSK_25: _Modcod.ValueType  # 3
    FE_SAT_QPSK_12: _Modcod.ValueType  # 4
    FE_SAT_QPSK_35: _Modcod.ValueType  # 5
    FE_SAT_QPSK_23: _Modcod.ValueType  # 6
    FE_SAT_QPSK_34: _Modcod.ValueType  # 7
    FE_SAT_QPSK_45: _Modcod.ValueType  # 8
    FE_SAT_QPSK_56: _Modcod.ValueType  # 9
    FE_SAT_QPSK_89: _Modcod.ValueType  # 10
    FE_SAT_QPSK_910: _Modcod.ValueType  # 11
    FE_SAT_8PSK_35: _Modcod.ValueType  # 12
    FE_SAT_8PSK_23: _Modcod.ValueType  # 13
    FE_SAT_8PSK_34: _Modcod.ValueType  # 14
    FE_SAT_8PSK_56: _Modcod.ValueType  # 15
    FE_SAT_8PSK_89: _Modcod.ValueType  # 16
    FE_SAT_8PSK_910: _Modcod.ValueType  # 17
    FE_SAT_16APSK_23: _Modcod.ValueType  # 18
    FE_SAT_16APSK_34: _Modcod.ValueType  # 19
    FE_SAT_16APSK_45: _Modcod.ValueType  # 20
    FE_SAT_16APSK_56: _Modcod.ValueType  # 21
    FE_SAT_16APSK_89: _Modcod.ValueType  # 22
    FE_SAT_16APSK_910: _Modcod.ValueType  # 23
    FE_SAT_32APSK_34: _Modcod.ValueType  # 24
    FE_SAT_32APSK_45: _Modcod.ValueType  # 25
    FE_SAT_32APSK_56: _Modcod.ValueType  # 26
    FE_SAT_32APSK_89: _Modcod.ValueType  # 27
    FE_SAT_32APSK_910: _Modcod.ValueType  # 28
    FE_SAT_MODCODE_UNKNOWN: _Modcod.ValueType  # 29
    FE_SAT_MODCODE_UNKNOWN_1E: _Modcod.ValueType  # 30
    FE_SAT_MODCODE_UNKNOWN_1F: _Modcod.ValueType  # 31
    FE_SAT_DVBS1_QPSK_12: _Modcod.ValueType  # 32
    """----------------------------------------"""
    FE_SAT_DVBS1_QPSK_23: _Modcod.ValueType  # 33
    FE_SAT_DVBS1_QPSK_34: _Modcod.ValueType  # 34
    FE_SAT_DVBS1_QPSK_56: _Modcod.ValueType  # 35
    FE_SAT_DVBS1_QPSK_67: _Modcod.ValueType  # 36
    FE_SAT_DVBS1_QPSK_78: _Modcod.ValueType  # 37
    FE_SAT_MODCODE_UNKNOWN_26: _Modcod.ValueType  # 38
    FE_SAT_MODCODE_UNKNOWN_27: _Modcod.ValueType  # 39
    FE_SAT_MODCODE_UNKNOWN_28: _Modcod.ValueType  # 40
    FE_SAT_MODCODE_UNKNOWN_29: _Modcod.ValueType  # 41
    FE_SAT_MODCODE_UNKNOWN_2A: _Modcod.ValueType  # 42
    FE_SAT_MODCODE_UNKNOWN_2B: _Modcod.ValueType  # 43
    FE_SAT_MODCODE_UNKNOWN_2C: _Modcod.ValueType  # 44
    FE_SAT_MODCODE_UNKNOWN_2D: _Modcod.ValueType  # 45
    FE_SAT_MODCODE_UNKNOWN_2E: _Modcod.ValueType  # 46
    FE_SAT_MODCODE_UNKNOWN_2F: _Modcod.ValueType  # 47
    FE_SAT_MODCODE_UNKNOWN_30: _Modcod.ValueType  # 48
    FE_SAT_MODCODE_UNKNOWN_31: _Modcod.ValueType  # 49
    FE_SAT_MODCODE_UNKNOWN_32: _Modcod.ValueType  # 50
    FE_SAT_MODCODE_UNKNOWN_33: _Modcod.ValueType  # 51
    FE_SAT_MODCODE_UNKNOWN_34: _Modcod.ValueType  # 52
    FE_SAT_MODCODE_UNKNOWN_35: _Modcod.ValueType  # 53
    FE_SAT_MODCODE_UNKNOWN_36: _Modcod.ValueType  # 54
    FE_SAT_MODCODE_UNKNOWN_37: _Modcod.ValueType  # 55
    FE_SAT_MODCODE_UNKNOWN_38: _Modcod.ValueType  # 56
    FE_SAT_MODCODE_UNKNOWN_39: _Modcod.ValueType  # 57
    FE_SAT_MODCODE_UNKNOWN_3A: _Modcod.ValueType  # 58
    FE_SAT_MODCODE_UNKNOWN_3B: _Modcod.ValueType  # 59
    FE_SAT_MODCODE_UNKNOWN_3C: _Modcod.ValueType  # 60
    FE_SAT_MODCODE_UNKNOWN_3D: _Modcod.ValueType  # 61
    FE_SAT_MODCODE_UNKNOWN_3E: _Modcod.ValueType  # 62
    FE_SAT_MODCODE_UNKNOWN_3F: _Modcod.ValueType  # 63
    FE_SATX_VLSNR1: _Modcod.ValueType  # 64
    """----------------------------------------"""
    FE_SATX_VLSNR2: _Modcod.ValueType  # 65
    FE_SATX_QPSK_13_45: _Modcod.ValueType  # 66
    FE_SATX_QPSK_9_20: _Modcod.ValueType  # 67
    FE_SATX_QPSK_11_20: _Modcod.ValueType  # 68
    FE_SATX_8APSK_5_9_L: _Modcod.ValueType  # 69
    FE_SATX_8APSK_26_45_L: _Modcod.ValueType  # 70
    FE_SATX_8PSK_23_36: _Modcod.ValueType  # 71
    FE_SATX_8PSK_25_36: _Modcod.ValueType  # 72
    FE_SATX_8PSK_13_18: _Modcod.ValueType  # 73
    FE_SATX_16APSK_1_2_L: _Modcod.ValueType  # 74
    FE_SATX_16APSK_8_15_L: _Modcod.ValueType  # 75
    FE_SATX_16APSK_5_9_L: _Modcod.ValueType  # 76
    FE_SATX_16APSK_26_45: _Modcod.ValueType  # 77
    FE_SATX_16APSK_3_5: _Modcod.ValueType  # 78
    FE_SATX_16APSK_3_5_L: _Modcod.ValueType  # 79
    FE_SATX_16APSK_28_45: _Modcod.ValueType  # 80
    FE_SATX_16APSK_23_36: _Modcod.ValueType  # 81
    FE_SATX_16APSK_2_3_L: _Modcod.ValueType  # 82
    FE_SATX_16APSK_25_36: _Modcod.ValueType  # 83
    FE_SATX_16APSK_13_18: _Modcod.ValueType  # 84
    FE_SATX_16APSK_7_9: _Modcod.ValueType  # 85
    FE_SATX_16APSK_77_90: _Modcod.ValueType  # 86
    FE_SATX_32APSK_2_3_L: _Modcod.ValueType  # 87
    FE_SATX_32APSK_R_58: _Modcod.ValueType  # 88
    FE_SATX_32APSK_32_45: _Modcod.ValueType  # 89
    FE_SATX_32APSK_11_15: _Modcod.ValueType  # 90
    FE_SATX_32APSK_7_9: _Modcod.ValueType  # 91
    FE_SATX_64APSK_32_45_L: _Modcod.ValueType  # 92
    FE_SATX_64APSK_11_15: _Modcod.ValueType  # 93
    FE_SATX_64APSK_R_5E: _Modcod.ValueType  # 94
    FE_SATX_64APSK_7_9: _Modcod.ValueType  # 95
    FE_SATX_64APSK_R_60: _Modcod.ValueType  # 96
    FE_SATX_64APSK_4_5: _Modcod.ValueType  # 97
    FE_SATX_64APSK_R_62: _Modcod.ValueType  # 98
    FE_SATX_64APSK_5_6: _Modcod.ValueType  # 99
    FE_SATX_128APSK_3_4: _Modcod.ValueType  # 100
    FE_SATX_128APSK_7_9: _Modcod.ValueType  # 101
    FE_SATX_256APSK_29_45_L: _Modcod.ValueType  # 102
    FE_SATX_256APSK_2_3_L: _Modcod.ValueType  # 103
    FE_SATX_256APSK_31_45_L: _Modcod.ValueType  # 104
    FE_SATX_256APSK_32_45: _Modcod.ValueType  # 105
    FE_SATX_256APSK_11_15_L: _Modcod.ValueType  # 106
    FE_SATX_256APSK_3_4: _Modcod.ValueType  # 107
    FE_SATX_QPSK_11_45: _Modcod.ValueType  # 108
    FE_SATX_QPSK_4_15: _Modcod.ValueType  # 109
    FE_SATX_QPSK_14_45: _Modcod.ValueType  # 110
    FE_SATX_QPSK_7_15: _Modcod.ValueType  # 111
    FE_SATX_QPSK_8_15: _Modcod.ValueType  # 112
    FE_SATX_QPSK_32_45: _Modcod.ValueType  # 113
    FE_SATX_8PSK_7_15: _Modcod.ValueType  # 114
    FE_SATX_8PSK_8_15: _Modcod.ValueType  # 115
    FE_SATX_8PSK_26_45: _Modcod.ValueType  # 116
    FE_SATX_8PSK_32_45: _Modcod.ValueType  # 117
    FE_SATX_16APSK_7_15: _Modcod.ValueType  # 118
    FE_SATX_16APSK_8_15: _Modcod.ValueType  # 119
    FE_SATX_16APSK_26_45_S: _Modcod.ValueType  # 120
    FE_SATX_16APSK_3_5_S: _Modcod.ValueType  # 121
    FE_SATX_16APSK_32_45: _Modcod.ValueType  # 122
    FE_SATX_32APSK_2_3: _Modcod.ValueType  # 123
    FE_SATX_32APSK_32_45_S: _Modcod.ValueType  # 124
    FE_SATX_8PSK: _Modcod.ValueType  # 125
    """----------------------------------------"""
    FE_SATX_32APSK: _Modcod.ValueType  # 126
    FE_SATX_256APSK: _Modcod.ValueType  # 127
    """POFF Modes"""
    FE_SATX_16APSK: _Modcod.ValueType  # 128
    FE_SATX_64APSK: _Modcod.ValueType  # 129
    FE_SATX_1024APSK: _Modcod.ValueType  # 130
    """PON Modes"""
    FE_SATX_8PSK_2: _Modcod.ValueType  # 131
    FE_SATX_16APSK_2: _Modcod.ValueType  # 132
    """Modcods sharing PLS value with VLSNR modcods"""
    FE_SAT_MODCODE_UNDETECTED: _Modcod.ValueType  # 133
    """Used to report an unknown/undetected modcod"""
    FE_SAT_MODCODE_MAX: _Modcod.ValueType  # 134
    """Only used for range checking"""

class Modcod(_Modcod, metaclass=_ModcodEnumTypeWrapper):
    """Copy pasted from Oxford driver"""

FE_SAT_DUMMY_PLF: Modcod.ValueType  # 0
"""
0x00..1F: Legacy list; DVBS2
0x20..3F: DVBS1
0x40..7F: DVBS2-X With:  _S: Short frame (only here to make it work compile; otherwise there will be a redefinition of enumerator)
_L: Linear constellation;
_R_xx: reserved + Modcode number hex   Pon; Poff Pilots configuration
"""
FE_SAT_QPSK_14: Modcod.ValueType  # 1
FE_SAT_QPSK_13: Modcod.ValueType  # 2
FE_SAT_QPSK_25: Modcod.ValueType  # 3
FE_SAT_QPSK_12: Modcod.ValueType  # 4
FE_SAT_QPSK_35: Modcod.ValueType  # 5
FE_SAT_QPSK_23: Modcod.ValueType  # 6
FE_SAT_QPSK_34: Modcod.ValueType  # 7
FE_SAT_QPSK_45: Modcod.ValueType  # 8
FE_SAT_QPSK_56: Modcod.ValueType  # 9
FE_SAT_QPSK_89: Modcod.ValueType  # 10
FE_SAT_QPSK_910: Modcod.ValueType  # 11
FE_SAT_8PSK_35: Modcod.ValueType  # 12
FE_SAT_8PSK_23: Modcod.ValueType  # 13
FE_SAT_8PSK_34: Modcod.ValueType  # 14
FE_SAT_8PSK_56: Modcod.ValueType  # 15
FE_SAT_8PSK_89: Modcod.ValueType  # 16
FE_SAT_8PSK_910: Modcod.ValueType  # 17
FE_SAT_16APSK_23: Modcod.ValueType  # 18
FE_SAT_16APSK_34: Modcod.ValueType  # 19
FE_SAT_16APSK_45: Modcod.ValueType  # 20
FE_SAT_16APSK_56: Modcod.ValueType  # 21
FE_SAT_16APSK_89: Modcod.ValueType  # 22
FE_SAT_16APSK_910: Modcod.ValueType  # 23
FE_SAT_32APSK_34: Modcod.ValueType  # 24
FE_SAT_32APSK_45: Modcod.ValueType  # 25
FE_SAT_32APSK_56: Modcod.ValueType  # 26
FE_SAT_32APSK_89: Modcod.ValueType  # 27
FE_SAT_32APSK_910: Modcod.ValueType  # 28
FE_SAT_MODCODE_UNKNOWN: Modcod.ValueType  # 29
FE_SAT_MODCODE_UNKNOWN_1E: Modcod.ValueType  # 30
FE_SAT_MODCODE_UNKNOWN_1F: Modcod.ValueType  # 31
FE_SAT_DVBS1_QPSK_12: Modcod.ValueType  # 32
"""----------------------------------------"""
FE_SAT_DVBS1_QPSK_23: Modcod.ValueType  # 33
FE_SAT_DVBS1_QPSK_34: Modcod.ValueType  # 34
FE_SAT_DVBS1_QPSK_56: Modcod.ValueType  # 35
FE_SAT_DVBS1_QPSK_67: Modcod.ValueType  # 36
FE_SAT_DVBS1_QPSK_78: Modcod.ValueType  # 37
FE_SAT_MODCODE_UNKNOWN_26: Modcod.ValueType  # 38
FE_SAT_MODCODE_UNKNOWN_27: Modcod.ValueType  # 39
FE_SAT_MODCODE_UNKNOWN_28: Modcod.ValueType  # 40
FE_SAT_MODCODE_UNKNOWN_29: Modcod.ValueType  # 41
FE_SAT_MODCODE_UNKNOWN_2A: Modcod.ValueType  # 42
FE_SAT_MODCODE_UNKNOWN_2B: Modcod.ValueType  # 43
FE_SAT_MODCODE_UNKNOWN_2C: Modcod.ValueType  # 44
FE_SAT_MODCODE_UNKNOWN_2D: Modcod.ValueType  # 45
FE_SAT_MODCODE_UNKNOWN_2E: Modcod.ValueType  # 46
FE_SAT_MODCODE_UNKNOWN_2F: Modcod.ValueType  # 47
FE_SAT_MODCODE_UNKNOWN_30: Modcod.ValueType  # 48
FE_SAT_MODCODE_UNKNOWN_31: Modcod.ValueType  # 49
FE_SAT_MODCODE_UNKNOWN_32: Modcod.ValueType  # 50
FE_SAT_MODCODE_UNKNOWN_33: Modcod.ValueType  # 51
FE_SAT_MODCODE_UNKNOWN_34: Modcod.ValueType  # 52
FE_SAT_MODCODE_UNKNOWN_35: Modcod.ValueType  # 53
FE_SAT_MODCODE_UNKNOWN_36: Modcod.ValueType  # 54
FE_SAT_MODCODE_UNKNOWN_37: Modcod.ValueType  # 55
FE_SAT_MODCODE_UNKNOWN_38: Modcod.ValueType  # 56
FE_SAT_MODCODE_UNKNOWN_39: Modcod.ValueType  # 57
FE_SAT_MODCODE_UNKNOWN_3A: Modcod.ValueType  # 58
FE_SAT_MODCODE_UNKNOWN_3B: Modcod.ValueType  # 59
FE_SAT_MODCODE_UNKNOWN_3C: Modcod.ValueType  # 60
FE_SAT_MODCODE_UNKNOWN_3D: Modcod.ValueType  # 61
FE_SAT_MODCODE_UNKNOWN_3E: Modcod.ValueType  # 62
FE_SAT_MODCODE_UNKNOWN_3F: Modcod.ValueType  # 63
FE_SATX_VLSNR1: Modcod.ValueType  # 64
"""----------------------------------------"""
FE_SATX_VLSNR2: Modcod.ValueType  # 65
FE_SATX_QPSK_13_45: Modcod.ValueType  # 66
FE_SATX_QPSK_9_20: Modcod.ValueType  # 67
FE_SATX_QPSK_11_20: Modcod.ValueType  # 68
FE_SATX_8APSK_5_9_L: Modcod.ValueType  # 69
FE_SATX_8APSK_26_45_L: Modcod.ValueType  # 70
FE_SATX_8PSK_23_36: Modcod.ValueType  # 71
FE_SATX_8PSK_25_36: Modcod.ValueType  # 72
FE_SATX_8PSK_13_18: Modcod.ValueType  # 73
FE_SATX_16APSK_1_2_L: Modcod.ValueType  # 74
FE_SATX_16APSK_8_15_L: Modcod.ValueType  # 75
FE_SATX_16APSK_5_9_L: Modcod.ValueType  # 76
FE_SATX_16APSK_26_45: Modcod.ValueType  # 77
FE_SATX_16APSK_3_5: Modcod.ValueType  # 78
FE_SATX_16APSK_3_5_L: Modcod.ValueType  # 79
FE_SATX_16APSK_28_45: Modcod.ValueType  # 80
FE_SATX_16APSK_23_36: Modcod.ValueType  # 81
FE_SATX_16APSK_2_3_L: Modcod.ValueType  # 82
FE_SATX_16APSK_25_36: Modcod.ValueType  # 83
FE_SATX_16APSK_13_18: Modcod.ValueType  # 84
FE_SATX_16APSK_7_9: Modcod.ValueType  # 85
FE_SATX_16APSK_77_90: Modcod.ValueType  # 86
FE_SATX_32APSK_2_3_L: Modcod.ValueType  # 87
FE_SATX_32APSK_R_58: Modcod.ValueType  # 88
FE_SATX_32APSK_32_45: Modcod.ValueType  # 89
FE_SATX_32APSK_11_15: Modcod.ValueType  # 90
FE_SATX_32APSK_7_9: Modcod.ValueType  # 91
FE_SATX_64APSK_32_45_L: Modcod.ValueType  # 92
FE_SATX_64APSK_11_15: Modcod.ValueType  # 93
FE_SATX_64APSK_R_5E: Modcod.ValueType  # 94
FE_SATX_64APSK_7_9: Modcod.ValueType  # 95
FE_SATX_64APSK_R_60: Modcod.ValueType  # 96
FE_SATX_64APSK_4_5: Modcod.ValueType  # 97
FE_SATX_64APSK_R_62: Modcod.ValueType  # 98
FE_SATX_64APSK_5_6: Modcod.ValueType  # 99
FE_SATX_128APSK_3_4: Modcod.ValueType  # 100
FE_SATX_128APSK_7_9: Modcod.ValueType  # 101
FE_SATX_256APSK_29_45_L: Modcod.ValueType  # 102
FE_SATX_256APSK_2_3_L: Modcod.ValueType  # 103
FE_SATX_256APSK_31_45_L: Modcod.ValueType  # 104
FE_SATX_256APSK_32_45: Modcod.ValueType  # 105
FE_SATX_256APSK_11_15_L: Modcod.ValueType  # 106
FE_SATX_256APSK_3_4: Modcod.ValueType  # 107
FE_SATX_QPSK_11_45: Modcod.ValueType  # 108
FE_SATX_QPSK_4_15: Modcod.ValueType  # 109
FE_SATX_QPSK_14_45: Modcod.ValueType  # 110
FE_SATX_QPSK_7_15: Modcod.ValueType  # 111
FE_SATX_QPSK_8_15: Modcod.ValueType  # 112
FE_SATX_QPSK_32_45: Modcod.ValueType  # 113
FE_SATX_8PSK_7_15: Modcod.ValueType  # 114
FE_SATX_8PSK_8_15: Modcod.ValueType  # 115
FE_SATX_8PSK_26_45: Modcod.ValueType  # 116
FE_SATX_8PSK_32_45: Modcod.ValueType  # 117
FE_SATX_16APSK_7_15: Modcod.ValueType  # 118
FE_SATX_16APSK_8_15: Modcod.ValueType  # 119
FE_SATX_16APSK_26_45_S: Modcod.ValueType  # 120
FE_SATX_16APSK_3_5_S: Modcod.ValueType  # 121
FE_SATX_16APSK_32_45: Modcod.ValueType  # 122
FE_SATX_32APSK_2_3: Modcod.ValueType  # 123
FE_SATX_32APSK_32_45_S: Modcod.ValueType  # 124
FE_SATX_8PSK: Modcod.ValueType  # 125
"""----------------------------------------"""
FE_SATX_32APSK: Modcod.ValueType  # 126
FE_SATX_256APSK: Modcod.ValueType  # 127
"""POFF Modes"""
FE_SATX_16APSK: Modcod.ValueType  # 128
FE_SATX_64APSK: Modcod.ValueType  # 129
FE_SATX_1024APSK: Modcod.ValueType  # 130
"""PON Modes"""
FE_SATX_8PSK_2: Modcod.ValueType  # 131
FE_SATX_16APSK_2: Modcod.ValueType  # 132
"""Modcods sharing PLS value with VLSNR modcods"""
FE_SAT_MODCODE_UNDETECTED: Modcod.ValueType  # 133
"""Used to report an unknown/undetected modcod"""
FE_SAT_MODCODE_MAX: Modcod.ValueType  # 134
"""Only used for range checking"""
global___Modcod = Modcod

@typing.final
class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.int
    def __init__(
        self,
        *,
        status: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___Result = Result

@typing.final
class Nspe2Report(google.protobuf.message.Message):
    """! NSPE2 status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    FRAME_COUNT_FIELD_NUMBER: builtins.int
    BYTE_COUNT_FIELD_NUMBER: builtins.int
    CRC_ERROR_COUNT_FIELD_NUMBER: builtins.int
    SYNC_LOSS_COUNT_FIELD_NUMBER: builtins.int
    DATA_RATE_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    frame_count: builtins.int
    """!< Number of NSPE2 frames"""
    byte_count: builtins.int
    """!< Number of NSPE2 decapsulation errors type A"""
    crc_error_count: builtins.int
    """!< Number of NSPE2 decapsulation errors type B"""
    sync_loss_count: builtins.int
    """!< Number of NSPE2 decapsulation errors type C"""
    data_rate: builtins.int
    """!< Data rate (bps)"""
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        frame_count: builtins.int = ...,
        byte_count: builtins.int = ...,
        crc_error_count: builtins.int = ...,
        sync_loss_count: builtins.int = ...,
        data_rate: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["byte_count", b"byte_count", "crc_error_count", b"crc_error_count", "data_rate", b"data_rate", "enabled", b"enabled", "frame_count", b"frame_count", "sync_loss_count", b"sync_loss_count"]) -> None: ...

global___Nspe2Report = Nspe2Report

@typing.final
class Noise(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINEAR_STRUCT_FIELD_NUMBER: builtins.int
    QUADRATIC_STRUCT_FIELD_NUMBER: builtins.int
    LINEAR_DATA_FIELD_NUMBER: builtins.int
    QUADRATIC_DATA_FIELD_NUMBER: builtins.int
    ABSOLUTE_LINEAR_DATA_FIELD_NUMBER: builtins.int
    QUADRATIC_DATA_FRAME_FIELD_NUMBER: builtins.int
    QUADRATIC_RADIAL_FIELD_NUMBER: builtins.int
    linear_struct: builtins.int
    """!< Linear noise normalized on the structures – e.g. NNOSPLHTx ?"""
    quadratic_struct: builtins.int
    """!< Quadratic noise normalized on the structures – e.g. NNOSPLHx"""
    linear_data: builtins.int
    """!< Linear noise normalized on the data – e.g. NNOSDATATx"""
    quadratic_data: builtins.int
    """!< Quadratic noise normalized on the data – e.g. NNOSDATA"""
    absolute_linear_data: builtins.int
    """!< Absolute linear noise on the data – e.g. NOSDATATx"""
    quadratic_data_frame: builtins.int
    """!< Quadratic noise normalized on the data and by Frame – e.g.NNOSFRAMEx"""
    quadratic_radial: builtins.int
    """!< Quadratic noise normalized radial – e.g. NNOSRAD1/0"""
    def __init__(
        self,
        *,
        linear_struct: builtins.int = ...,
        quadratic_struct: builtins.int = ...,
        linear_data: builtins.int = ...,
        quadratic_data: builtins.int = ...,
        absolute_linear_data: builtins.int = ...,
        quadratic_data_frame: builtins.int = ...,
        quadratic_radial: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["absolute_linear_data", b"absolute_linear_data", "linear_data", b"linear_data", "linear_struct", b"linear_struct", "quadratic_data", b"quadratic_data", "quadratic_data_frame", b"quadratic_data_frame", "quadratic_radial", b"quadratic_radial", "quadratic_struct", b"quadratic_struct"]) -> None: ...

global___Noise = Noise

@typing.final
class Channel(google.protobuf.message.Message):
    """Channel"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LockStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LockStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Channel._LockStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DL_NONE: Channel._LockStatus.ValueType  # 0
        DL_AUTO: Channel._LockStatus.ValueType  # 1
        DL_DVBS: Channel._LockStatus.ValueType  # 2
        DL_DVBS2: Channel._LockStatus.ValueType  # 3
        DL_DVBS2X: Channel._LockStatus.ValueType  # 4
        DL_UNLOCKED: Channel._LockStatus.ValueType  # 5

    class LockStatus(_LockStatus, metaclass=_LockStatusEnumTypeWrapper): ...
    DL_NONE: Channel.LockStatus.ValueType  # 0
    DL_AUTO: Channel.LockStatus.ValueType  # 1
    DL_DVBS: Channel.LockStatus.ValueType  # 2
    DL_DVBS2: Channel.LockStatus.ValueType  # 3
    DL_DVBS2X: Channel.LockStatus.ValueType  # 4
    DL_UNLOCKED: Channel.LockStatus.ValueType  # 5

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    LOCK_STATUS_FIELD_NUMBER: builtins.int
    LOCK_FREQUENCY_FIELD_NUMBER: builtins.int
    ACQUISITION_RANGE_FIELD_NUMBER: builtins.int
    SYMBOL_RATE_FIELD_NUMBER: builtins.int
    DVB_STANDARD_FIELD_NUMBER: builtins.int
    ROLL_OFF_FIELD_NUMBER: builtins.int
    PILOT_FIELD_NUMBER: builtins.int
    SPECTRAL_INVERSION_FIELD_NUMBER: builtins.int
    PLH_MODCOD_FIELD_NUMBER: builtins.int
    PLH_TYPE_FIELD_NUMBER: builtins.int
    NOISE_FIELD_NUMBER: builtins.int
    AGC1_ACCUMULATOR_FIELD_NUMBER: builtins.int
    AGC2_ACCUMULATOR_FIELD_NUMBER: builtins.int
    LDPC_ITERATION_NUMBER_FIELD_NUMBER: builtins.int
    LDPC_MAX_ITERATIONS_FIELD_NUMBER: builtins.int
    BBF_FRAMES_FIELD_NUMBER: builtins.int
    BBF_ERRORED_FRAMES_FIELD_NUMBER: builtins.int
    FER_FIELD_NUMBER: builtins.int
    CNR_FIELD_NUMBER: builtins.int
    NSPE2_FIELD_NUMBER: builtins.int
    CHANNEL_POWER_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    enabled: builtins.bool
    rf_source: builtins.int
    lock_status: global___Channel.LockStatus.ValueType
    lock_frequency: builtins.int
    acquisition_range: builtins.int
    symbol_rate: builtins.int
    dvb_standard: global___DVBStandard.ValueType
    roll_off: global___RollOffType.ValueType
    pilot: global___Pilot.ValueType
    spectral_inversion: global___SpectralInversion.ValueType
    plh_modcod: builtins.int
    """!< Current PLH_MODCOD, not stable"""
    plh_type: builtins.int
    """!< Current PLH_TYPE, not stable"""
    agc1_accumulator: builtins.int
    """!< AGC1 accumulator – e.g. AGCIQINx or other"""
    agc2_accumulator: builtins.int
    """!< AGC2 accumulator – e.g. AGC2Ix or other"""
    ldpc_iteration_number: builtins.int
    """!< LDPC iteration number performed – e.g. STATUSITER or other"""
    ldpc_max_iterations: builtins.int
    """!< LDPC maximum iteration number performed – e.g. STATUSMAXITER or other"""
    bbf_frames: builtins.int
    """!< Number of BBF frames since last read"""
    bbf_errored_frames: builtins.int
    """!< Number of errored BBF frames since last read - based on Oxford BB frame counter"""
    fer: builtins.float
    cnr: builtins.float
    channel_power: builtins.int
    @property
    def noise(self) -> global___Noise: ...
    @property
    def nspe2(self) -> global___Nspe2Report: ...
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        enabled: builtins.bool = ...,
        rf_source: builtins.int = ...,
        lock_status: global___Channel.LockStatus.ValueType = ...,
        lock_frequency: builtins.int = ...,
        acquisition_range: builtins.int = ...,
        symbol_rate: builtins.int = ...,
        dvb_standard: global___DVBStandard.ValueType = ...,
        roll_off: global___RollOffType.ValueType = ...,
        pilot: global___Pilot.ValueType = ...,
        spectral_inversion: global___SpectralInversion.ValueType = ...,
        plh_modcod: builtins.int = ...,
        plh_type: builtins.int = ...,
        noise: global___Noise | None = ...,
        agc1_accumulator: builtins.int = ...,
        agc2_accumulator: builtins.int = ...,
        ldpc_iteration_number: builtins.int = ...,
        ldpc_max_iterations: builtins.int = ...,
        bbf_frames: builtins.int = ...,
        bbf_errored_frames: builtins.int = ...,
        fer: builtins.float = ...,
        cnr: builtins.float = ...,
        nspe2: global___Nspe2Report | None = ...,
        channel_power: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["noise", b"noise", "nspe2", b"nspe2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acquisition_range", b"acquisition_range", "agc1_accumulator", b"agc1_accumulator", "agc2_accumulator", b"agc2_accumulator", "bbf_errored_frames", b"bbf_errored_frames", "bbf_frames", b"bbf_frames", "channel_index", b"channel_index", "channel_power", b"channel_power", "cnr", b"cnr", "dvb_standard", b"dvb_standard", "enabled", b"enabled", "fer", b"fer", "ldpc_iteration_number", b"ldpc_iteration_number", "ldpc_max_iterations", b"ldpc_max_iterations", "lock_frequency", b"lock_frequency", "lock_status", b"lock_status", "noise", b"noise", "nspe2", b"nspe2", "pilot", b"pilot", "plh_modcod", b"plh_modcod", "plh_type", b"plh_type", "rf_source", b"rf_source", "roll_off", b"roll_off", "spectral_inversion", b"spectral_inversion", "symbol_rate", b"symbol_rate"]) -> None: ...

global___Channel = Channel

@typing.final
class DataPort(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    IP_NETMASK_FIELD_NUMBER: builtins.int
    IP_DEF_GATEWAY_FIELD_NUMBER: builtins.int
    MAC_DEF_GATEWAY_FIELD_NUMBER: builtins.int
    VLAN_FIELD_NUMBER: builtins.int
    mac_address: builtins.bytes
    ip_address: builtins.str
    ip_netmask: builtins.str
    ip_def_gateway: builtins.str
    mac_def_gateway: builtins.bytes
    vlan: builtins.int
    def __init__(
        self,
        *,
        mac_address: builtins.bytes = ...,
        ip_address: builtins.str = ...,
        ip_netmask: builtins.str = ...,
        ip_def_gateway: builtins.str = ...,
        mac_def_gateway: builtins.bytes = ...,
        vlan: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip_address", b"ip_address", "ip_def_gateway", b"ip_def_gateway", "ip_netmask", b"ip_netmask", "mac_address", b"mac_address", "mac_def_gateway", b"mac_def_gateway", "vlan", b"vlan"]) -> None: ...

global___DataPort = DataPort

@typing.final
class BoardInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOARD_INDEX_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DEMODULATOR_CHIP_VERSION_FIELD_NUMBER: builtins.int
    DATA_PORT_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    BIT_STATUS_FIELD_NUMBER: builtins.int
    COMMUNICATION_STATUS_FIELD_NUMBER: builtins.int
    BCA_VERSION_FIELD_NUMBER: builtins.int
    board_index: builtins.int
    status: global___BoardStatus.ValueType
    demodulator_chip_version: builtins.str
    temperature: builtins.float
    bit_status: builtins.int
    communication_status: global___CommunicationStatus.ValueType
    bca_version: builtins.str
    @property
    def data_port(self) -> global___DataPort: ...
    def __init__(
        self,
        *,
        board_index: builtins.int = ...,
        status: global___BoardStatus.ValueType = ...,
        demodulator_chip_version: builtins.str = ...,
        data_port: global___DataPort | None = ...,
        temperature: builtins.float = ...,
        bit_status: builtins.int = ...,
        communication_status: global___CommunicationStatus.ValueType = ...,
        bca_version: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data_port", b"data_port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bca_version", b"bca_version", "bit_status", b"bit_status", "board_index", b"board_index", "communication_status", b"communication_status", "data_port", b"data_port", "demodulator_chip_version", b"demodulator_chip_version", "status", b"status", "temperature", b"temperature"]) -> None: ...

global___BoardInfo = BoardInfo

@typing.final
class ChannelConfiguration(google.protobuf.message.Message):
    """Channel configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SearchMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SearchModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration._SearchMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SAT_AUTO: ChannelConfiguration._SearchMode.ValueType  # 0
        SAT_COLD: ChannelConfiguration._SearchMode.ValueType  # 1
        """the SR is known"""

    class SearchMode(_SearchMode, metaclass=_SearchModeEnumTypeWrapper): ...
    SAT_AUTO: ChannelConfiguration.SearchMode.ValueType  # 0
    SAT_COLD: ChannelConfiguration.SearchMode.ValueType  # 1
    """the SR is known"""

    class _EncapMethod:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EncapMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration._EncapMethod.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EM_NSPE2: ChannelConfiguration._EncapMethod.ValueType  # 0
        """! default, as it is derived from NVS"""
        EM_TC1X: ChannelConfiguration._EncapMethod.ValueType  # 1
        EM_TC1X_SLICES: ChannelConfiguration._EncapMethod.ValueType  # 2
        EM_TC1X_TV: ChannelConfiguration._EncapMethod.ValueType  # 3
        EM_SRX_GSE: ChannelConfiguration._EncapMethod.ValueType  # 4

    class EncapMethod(_EncapMethod, metaclass=_EncapMethodEnumTypeWrapper):
        """! encapsulation method"""

    EM_NSPE2: ChannelConfiguration.EncapMethod.ValueType  # 0
    """! default, as it is derived from NVS"""
    EM_TC1X: ChannelConfiguration.EncapMethod.ValueType  # 1
    EM_TC1X_SLICES: ChannelConfiguration.EncapMethod.ValueType  # 2
    EM_TC1X_TV: ChannelConfiguration.EncapMethod.ValueType  # 3
    EM_SRX_GSE: ChannelConfiguration.EncapMethod.ValueType  # 4

    @typing.final
    class ACMGenerator(google.protobuf.message.Message):
        """! ACM messages generator 8X4 (periodic and Fast)"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Source:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _SourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.ACMGenerator._Source.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            AMS_INVALID: ChannelConfiguration.ACMGenerator._Source.ValueType  # 0
            AMS_FPGA: ChannelConfiguration.ACMGenerator._Source.ValueType  # 1
            AMS_CPU: ChannelConfiguration.ACMGenerator._Source.ValueType  # 2

        class Source(_Source, metaclass=_SourceEnumTypeWrapper): ...
        AMS_INVALID: ChannelConfiguration.ACMGenerator.Source.ValueType  # 0
        AMS_FPGA: ChannelConfiguration.ACMGenerator.Source.ValueType  # 1
        AMS_CPU: ChannelConfiguration.ACMGenerator.Source.ValueType  # 2

        @typing.final
        class Destination(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            MAC_ADDRESS_FIELD_NUMBER: builtins.int
            IP_ADDRESS_FIELD_NUMBER: builtins.int
            PORT_FIELD_NUMBER: builtins.int
            mac_address: builtins.bytes
            """!< MAC address"""
            ip_address: builtins.bytes
            """!< IP address"""
            port: builtins.int
            """!< UDP port"""
            def __init__(
                self,
                *,
                mac_address: builtins.bytes = ...,
                ip_address: builtins.bytes = ...,
                port: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["ip_address", b"ip_address", "mac_address", b"mac_address", "port", b"port"]) -> None: ...

        ENABLED_FIELD_NUMBER: builtins.int
        T_INTERVAL_FIELD_NUMBER: builtins.int
        DROP_LIMIT_FIELD_NUMBER: builtins.int
        SOURCE_FIELD_NUMBER: builtins.int
        DESTINATION_FIELD_NUMBER: builtins.int
        SAMPLE_INTERVAL_FIELD_NUMBER: builtins.int
        HOLD_OFF_FIELD_NUMBER: builtins.int
        ERR_COLLECT_SPEED_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        t_interval: builtins.int
        """!< T_interval, msec (not less than 4000 msec)"""
        drop_limit: builtins.int
        """!< Drop limit"""
        source: global___ChannelConfiguration.ACMGenerator.Source.ValueType
        """!< Fast messages Generator Source - FPGA or SW (per board max 2 FPGA, if violated, SNMP NACK)"""
        sample_interval: builtins.int
        """!< Pilot SNR sampling interval by the FPGA, in units of msec"""
        hold_off: builtins.int
        """!<  Urgent carrier status report FPGA holdoff timer, in units of msec"""
        err_collect_speed: builtins.int
        """!< NOSPLH_BETA"""
        @property
        def destination(self) -> global___ChannelConfiguration.ACMGenerator.Destination:
            """!< Destination"""

        def __init__(
            self,
            *,
            enabled: builtins.bool = ...,
            t_interval: builtins.int = ...,
            drop_limit: builtins.int = ...,
            source: global___ChannelConfiguration.ACMGenerator.Source.ValueType = ...,
            destination: global___ChannelConfiguration.ACMGenerator.Destination | None = ...,
            sample_interval: builtins.int = ...,
            hold_off: builtins.int = ...,
            err_collect_speed: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["destination", b"destination"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["destination", b"destination", "drop_limit", b"drop_limit", "enabled", b"enabled", "err_collect_speed", b"err_collect_speed", "hold_off", b"hold_off", "sample_interval", b"sample_interval", "source", b"source", "t_interval", b"t_interval"]) -> None: ...

    @typing.final
    class NSPE2(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class Destination(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            MAC_ADDRESS_FIELD_NUMBER: builtins.int
            mac_address: builtins.bytes
            """!< MAC address"""
            def __init__(
                self,
                *,
                mac_address: builtins.bytes = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["mac_address", b"mac_address"]) -> None: ...

        ENABLED_FIELD_NUMBER: builtins.int
        DESTINATION_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        @property
        def destination(self) -> global___ChannelConfiguration.NSPE2.Destination: ...
        def __init__(
            self,
            *,
            enabled: builtins.bool = ...,
            destination: global___ChannelConfiguration.NSPE2.Destination | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["destination", b"destination"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["destination", b"destination", "enabled", b"enabled"]) -> None: ...

    @typing.final
    class SrxGse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _GseLabelType:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _GseLabelTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.SrxGse._GseLabelType.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            GSE_LABEL_6BYTE: ChannelConfiguration.SrxGse._GseLabelType.ValueType  # 0
            GSE_LABEL_3BYTE: ChannelConfiguration.SrxGse._GseLabelType.ValueType  # 1
            GSE_LABEL_NO_LABEL: ChannelConfiguration.SrxGse._GseLabelType.ValueType  # 2

        class GseLabelType(_GseLabelType, metaclass=_GseLabelTypeEnumTypeWrapper): ...
        GSE_LABEL_6BYTE: ChannelConfiguration.SrxGse.GseLabelType.ValueType  # 0
        GSE_LABEL_3BYTE: ChannelConfiguration.SrxGse.GseLabelType.ValueType  # 1
        GSE_LABEL_NO_LABEL: ChannelConfiguration.SrxGse.GseLabelType.ValueType  # 2

        class _BbfSource:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _BbfSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.SrxGse._BbfSource.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            SOURCE_NOT_VALID: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 0
            SOURCE_TS1: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 1
            SOURCE_TS2: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 2
            SOURCE_TS3: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 3
            SOURCE_TS4: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 4
            SOURCE_TS5: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 5
            SOURCE_TS6: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 6
            SOURCE_TS7: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 7
            SOURCE_TS8: ChannelConfiguration.SrxGse._BbfSource.ValueType  # 8

        class BbfSource(_BbfSource, metaclass=_BbfSourceEnumTypeWrapper): ...
        SOURCE_NOT_VALID: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 0
        SOURCE_TS1: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 1
        SOURCE_TS2: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 2
        SOURCE_TS3: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 3
        SOURCE_TS4: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 4
        SOURCE_TS5: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 5
        SOURCE_TS6: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 6
        SOURCE_TS7: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 7
        SOURCE_TS8: ChannelConfiguration.SrxGse.BbfSource.ValueType  # 8

        @typing.final
        class Destination(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            MAC_ADDRESS_FIELD_NUMBER: builtins.int
            LABEL_TYPE_FIELD_NUMBER: builtins.int
            mac_address: builtins.bytes
            """!< MAC address"""
            label_type: global___ChannelConfiguration.SrxGse.GseLabelType.ValueType
            """!< Label Type"""
            def __init__(
                self,
                *,
                mac_address: builtins.bytes = ...,
                label_type: global___ChannelConfiguration.SrxGse.GseLabelType.ValueType = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["label_type", b"label_type", "mac_address", b"mac_address"]) -> None: ...

        ENABLED_FIELD_NUMBER: builtins.int
        DESTINATION_FIELD_NUMBER: builtins.int
        ISI_FIELD_NUMBER: builtins.int
        TS_SOURCE_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        isi: builtins.int
        """!< valid range is 0-255"""
        ts_source: global___ChannelConfiguration.SrxGse.BbfSource.ValueType
        @property
        def destination(self) -> global___ChannelConfiguration.SrxGse.Destination: ...
        def __init__(
            self,
            *,
            enabled: builtins.bool = ...,
            destination: global___ChannelConfiguration.SrxGse.Destination | None = ...,
            isi: builtins.int = ...,
            ts_source: global___ChannelConfiguration.SrxGse.BbfSource.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["destination", b"destination"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["destination", b"destination", "enabled", b"enabled", "isi", b"isi", "ts_source", b"ts_source"]) -> None: ...

    @typing.final
    class Tc1ProEgress(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class NetworkInterface(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            MAC_ADDRESS_FIELD_NUMBER: builtins.int
            IP_ADDRESS_FIELD_NUMBER: builtins.int
            PORT_FIELD_NUMBER: builtins.int
            mac_address: builtins.bytes
            """!< MAC address"""
            ip_address: builtins.str
            """!< IP address"""
            port: builtins.int
            """!< UDP port"""
            def __init__(
                self,
                *,
                mac_address: builtins.bytes = ...,
                ip_address: builtins.str = ...,
                port: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["ip_address", b"ip_address", "mac_address", b"mac_address", "port", b"port"]) -> None: ...

        @typing.final
        class VLAN(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ENABLED_FIELD_NUMBER: builtins.int
            TAG_FIELD_NUMBER: builtins.int
            enabled: builtins.bool
            tag: builtins.int
            def __init__(
                self,
                *,
                enabled: builtins.bool = ...,
                tag: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["enabled", b"enabled", "tag", b"tag"]) -> None: ...

        ENABLED_FIELD_NUMBER: builtins.int
        DESTINATION_FIELD_NUMBER: builtins.int
        SOURCE_FIELD_NUMBER: builtins.int
        VLAN_FIELD_NUMBER: builtins.int
        DSCP_FIELD_NUMBER: builtins.int
        FORCE_BBF_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        dscp: builtins.int
        force_bbf: builtins.bool
        @property
        def destination(self) -> global___ChannelConfiguration.Tc1ProEgress.NetworkInterface: ...
        @property
        def source(self) -> global___ChannelConfiguration.Tc1ProEgress.NetworkInterface: ...
        @property
        def vlan(self) -> global___ChannelConfiguration.Tc1ProEgress.VLAN: ...
        def __init__(
            self,
            *,
            enabled: builtins.bool = ...,
            destination: global___ChannelConfiguration.Tc1ProEgress.NetworkInterface | None = ...,
            source: global___ChannelConfiguration.Tc1ProEgress.NetworkInterface | None = ...,
            vlan: global___ChannelConfiguration.Tc1ProEgress.VLAN | None = ...,
            dscp: builtins.int = ...,
            force_bbf: builtins.bool = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["destination", b"destination", "source", b"source", "vlan", b"vlan"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["destination", b"destination", "dscp", b"dscp", "enabled", b"enabled", "force_bbf", b"force_bbf", "source", b"source", "vlan", b"vlan"]) -> None: ...

    @typing.final
    class LnbConfig(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _LnbVoltage:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _LnbVoltageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.LnbConfig._LnbVoltage.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            V_OFF: ChannelConfiguration.LnbConfig._LnbVoltage.ValueType  # 0
            V_13V: ChannelConfiguration.LnbConfig._LnbVoltage.ValueType  # 1
            """<! vertical"""
            V_18V: ChannelConfiguration.LnbConfig._LnbVoltage.ValueType  # 2
            """<! horizontal"""

        class LnbVoltage(_LnbVoltage, metaclass=_LnbVoltageEnumTypeWrapper): ...
        V_OFF: ChannelConfiguration.LnbConfig.LnbVoltage.ValueType  # 0
        V_13V: ChannelConfiguration.LnbConfig.LnbVoltage.ValueType  # 1
        """<! vertical"""
        V_18V: ChannelConfiguration.LnbConfig.LnbVoltage.ValueType  # 2
        """<! horizontal"""

        class _Lnb22KHz:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _Lnb22KHzEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.LnbConfig._Lnb22KHz.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            T_OFF: ChannelConfiguration.LnbConfig._Lnb22KHz.ValueType  # 0
            """<! low"""
            T_ON: ChannelConfiguration.LnbConfig._Lnb22KHz.ValueType  # 1
            """<! high"""

        class Lnb22KHz(_Lnb22KHz, metaclass=_Lnb22KHzEnumTypeWrapper): ...
        T_OFF: ChannelConfiguration.LnbConfig.Lnb22KHz.ValueType  # 0
        """<! low"""
        T_ON: ChannelConfiguration.LnbConfig.Lnb22KHz.ValueType  # 1
        """<! high"""

        class _Lnb10MHz:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _Lnb10MHzEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChannelConfiguration.LnbConfig._Lnb10MHz.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            R_OFF: ChannelConfiguration.LnbConfig._Lnb10MHz.ValueType  # 0
            """<! pin high"""
            R_ON: ChannelConfiguration.LnbConfig._Lnb10MHz.ValueType  # 1
            """<! pin low"""

        class Lnb10MHz(_Lnb10MHz, metaclass=_Lnb10MHzEnumTypeWrapper): ...
        R_OFF: ChannelConfiguration.LnbConfig.Lnb10MHz.ValueType  # 0
        """<! pin high"""
        R_ON: ChannelConfiguration.LnbConfig.Lnb10MHz.ValueType  # 1
        """<! pin low"""

        LNB_VOLTAGE_FIELD_NUMBER: builtins.int
        LNB_TONE_FIELD_NUMBER: builtins.int
        LNB_1V_COMPENSATION_FIELD_NUMBER: builtins.int
        LNB_REFERENCE_FIELD_NUMBER: builtins.int
        lnb_voltage: global___ChannelConfiguration.LnbConfig.LnbVoltage.ValueType
        lnb_tone: global___ChannelConfiguration.LnbConfig.Lnb22KHz.ValueType
        lnb_1v_compensation: builtins.bool
        lnb_reference: global___ChannelConfiguration.LnbConfig.Lnb10MHz.ValueType
        def __init__(
            self,
            *,
            lnb_voltage: global___ChannelConfiguration.LnbConfig.LnbVoltage.ValueType = ...,
            lnb_tone: global___ChannelConfiguration.LnbConfig.Lnb22KHz.ValueType = ...,
            lnb_1v_compensation: builtins.bool = ...,
            lnb_reference: global___ChannelConfiguration.LnbConfig.Lnb10MHz.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["lnb_1v_compensation", b"lnb_1v_compensation", "lnb_reference", b"lnb_reference", "lnb_tone", b"lnb_tone", "lnb_voltage", b"lnb_voltage"]) -> None: ...

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    FREQUENCY_FIELD_NUMBER: builtins.int
    ACQUISITION_RANGE_FIELD_NUMBER: builtins.int
    SYMBOL_RATE_FIELD_NUMBER: builtins.int
    ROLL_OFF_FIELD_NUMBER: builtins.int
    GOLDEN_SEQUENCE_FIELD_NUMBER: builtins.int
    SEARCH_MODE_FIELD_NUMBER: builtins.int
    SEARCH_ENABLED_FIELD_NUMBER: builtins.int
    FORCE_RELOCK_FIELD_NUMBER: builtins.int
    ACM_FIELD_NUMBER: builtins.int
    NSPE2_FIELD_NUMBER: builtins.int
    ENCAP_METHOD_FIELD_NUMBER: builtins.int
    EGRESS_FIELD_NUMBER: builtins.int
    ANNEX_M_SLICES_FIELD_NUMBER: builtins.int
    LNB_FIELD_NUMBER: builtins.int
    SRX_GSE_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    enabled: builtins.bool
    rf_source: builtins.int
    frequency: builtins.int
    acquisition_range: builtins.int
    symbol_rate: builtins.int
    roll_off: global___RollOffType.ValueType
    golden_sequence: builtins.int
    """!< Golden sequence (PLSCRAMB_ROOT)"""
    search_mode: global___ChannelConfiguration.SearchMode.ValueType
    search_enabled: builtins.bool
    force_relock: builtins.bool
    encap_method: global___ChannelConfiguration.EncapMethod.ValueType
    """!< encapsulation demuxing flag"""
    @property
    def acm(self) -> global___ChannelConfiguration.ACMGenerator: ...
    @property
    def nspe2(self) -> global___ChannelConfiguration.NSPE2: ...
    @property
    def egress(self) -> global___ChannelConfiguration.Tc1ProEgress: ...
    @property
    def annex_m_slices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def lnb(self) -> global___ChannelConfiguration.LnbConfig: ...
    @property
    def srx_gse(self) -> global___ChannelConfiguration.SrxGse: ...
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        enabled: builtins.bool = ...,
        rf_source: builtins.int = ...,
        frequency: builtins.int = ...,
        acquisition_range: builtins.int = ...,
        symbol_rate: builtins.int = ...,
        roll_off: global___RollOffType.ValueType = ...,
        golden_sequence: builtins.int = ...,
        search_mode: global___ChannelConfiguration.SearchMode.ValueType = ...,
        search_enabled: builtins.bool = ...,
        force_relock: builtins.bool = ...,
        acm: global___ChannelConfiguration.ACMGenerator | None = ...,
        nspe2: global___ChannelConfiguration.NSPE2 | None = ...,
        encap_method: global___ChannelConfiguration.EncapMethod.ValueType = ...,
        egress: global___ChannelConfiguration.Tc1ProEgress | None = ...,
        annex_m_slices: collections.abc.Iterable[builtins.int] | None = ...,
        lnb: global___ChannelConfiguration.LnbConfig | None = ...,
        srx_gse: global___ChannelConfiguration.SrxGse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["acm", b"acm", "egress", b"egress", "lnb", b"lnb", "nspe2", b"nspe2", "srx_gse", b"srx_gse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acm", b"acm", "acquisition_range", b"acquisition_range", "annex_m_slices", b"annex_m_slices", "channel_index", b"channel_index", "egress", b"egress", "enabled", b"enabled", "encap_method", b"encap_method", "force_relock", b"force_relock", "frequency", b"frequency", "golden_sequence", b"golden_sequence", "lnb", b"lnb", "nspe2", b"nspe2", "rf_source", b"rf_source", "roll_off", b"roll_off", "search_enabled", b"search_enabled", "search_mode", b"search_mode", "srx_gse", b"srx_gse", "symbol_rate", b"symbol_rate"]) -> None: ...

global___ChannelConfiguration = ChannelConfiguration

@typing.final
class Cnr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    CNR_FIELD_NUMBER: builtins.int
    CHANNEL_POWER_FIELD_NUMBER: builtins.int
    BAND_POWER_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    cnr: builtins.float
    channel_power: builtins.float
    band_power: builtins.float
    rf_source: builtins.int
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        cnr: builtins.float = ...,
        channel_power: builtins.float = ...,
        band_power: builtins.float = ...,
        rf_source: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["band_power", b"band_power", "channel_index", b"channel_index", "channel_power", b"channel_power", "cnr", b"cnr", "rf_source", b"rf_source"]) -> None: ...

global___Cnr = Cnr

@typing.final
class MultiCnr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CNR_FIELD_NUMBER: builtins.int
    @property
    def cnr(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Cnr]: ...
    def __init__(
        self,
        *,
        cnr: collections.abc.Iterable[global___Cnr] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cnr", b"cnr"]) -> None: ...

global___MultiCnr = MultiCnr

@typing.final
class PeriodicReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    RF_PATH_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    PLH_MODCOD_FIELD_NUMBER: builtins.int
    PLH_TYPE_FIELD_NUMBER: builtins.int
    NOISE_FIELD_NUMBER: builtins.int
    AGC1_ACCUMULATOR_FIELD_NUMBER: builtins.int
    AGC2_ACCUMULATOR_FIELD_NUMBER: builtins.int
    LDPC_ITERATION_NUMBER_FIELD_NUMBER: builtins.int
    LDPC_MAX_ITERATIONS_FIELD_NUMBER: builtins.int
    BBF_FRAMES_FIELD_NUMBER: builtins.int
    BBF_ERRORED_FRAMES_FIELD_NUMBER: builtins.int
    RAW_CNR_FIELD_NUMBER: builtins.int
    TRANSLATED_CNR_FIELD_NUMBER: builtins.int
    CHANNEL_POWER_FIELD_NUMBER: builtins.int
    BAND_POWER_FIELD_NUMBER: builtins.int
    LOCK_FLAGS_FIELD_NUMBER: builtins.int
    MODCOD_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    rf_path: builtins.int
    locked: builtins.bool
    """!< yes/no"""
    plh_modcod: builtins.int
    """!< Current PLH_MODCOD, not stable"""
    plh_type: builtins.int
    """!< Current PLH_TYPE, not stable"""
    agc1_accumulator: builtins.int
    """!< AGC1 accumulator – e.g. AGCIQINx or other"""
    agc2_accumulator: builtins.int
    """!< AGC2 accumulator – e.g. AGC2Ix or other"""
    ldpc_iteration_number: builtins.int
    """!< LDPC iteration number performed – e.g. STATUSITER or other"""
    ldpc_max_iterations: builtins.int
    """!< LDPC maximum iteration number performed – e.g. STATUSMAXITER or other"""
    bbf_frames: builtins.int
    """!< Number of BBF frames since last read"""
    bbf_errored_frames: builtins.int
    """!< Number of errored BBF frames since last read - based on Oxford BB frame counter"""
    raw_cnr: builtins.int
    """!< raw CNR register value"""
    translated_cnr: builtins.float
    """!< translated CNR value"""
    channel_power: builtins.float
    """!< in 0.1 dBm - demod power"""
    band_power: builtins.float
    """!< in 0.1 dBm - entire band measurement"""
    lock_flags: builtins.int
    """!< LOCK_DEFINITIF|TUN_LOCKED|PKTDELIN_LOCK|LOCKEDVIT|AGCRF_LOCKED|PLL_LOCK|CAR_LOCK|TIMING_IS_LOCKED"""
    modcod: global___Modcod.ValueType
    """!< translated modcod,as in the LockReport"""
    @property
    def noise(self) -> global___Noise: ...
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        rf_path: builtins.int = ...,
        locked: builtins.bool = ...,
        plh_modcod: builtins.int = ...,
        plh_type: builtins.int = ...,
        noise: global___Noise | None = ...,
        agc1_accumulator: builtins.int = ...,
        agc2_accumulator: builtins.int = ...,
        ldpc_iteration_number: builtins.int = ...,
        ldpc_max_iterations: builtins.int = ...,
        bbf_frames: builtins.int = ...,
        bbf_errored_frames: builtins.int = ...,
        raw_cnr: builtins.int = ...,
        translated_cnr: builtins.float = ...,
        channel_power: builtins.float = ...,
        band_power: builtins.float = ...,
        lock_flags: builtins.int = ...,
        modcod: global___Modcod.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["noise", b"noise"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["agc1_accumulator", b"agc1_accumulator", "agc2_accumulator", b"agc2_accumulator", "band_power", b"band_power", "bbf_errored_frames", b"bbf_errored_frames", "bbf_frames", b"bbf_frames", "channel_index", b"channel_index", "channel_power", b"channel_power", "ldpc_iteration_number", b"ldpc_iteration_number", "ldpc_max_iterations", b"ldpc_max_iterations", "lock_flags", b"lock_flags", "locked", b"locked", "modcod", b"modcod", "noise", b"noise", "plh_modcod", b"plh_modcod", "plh_type", b"plh_type", "raw_cnr", b"raw_cnr", "rf_path", b"rf_path", "translated_cnr", b"translated_cnr"]) -> None: ...

global___PeriodicReport = PeriodicReport

@typing.final
class FullPeriodicReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    PERIODIC_REPORT_FIELD_NUMBER: builtins.int
    NSPE2_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    @property
    def periodic_report(self) -> global___PeriodicReport: ...
    @property
    def nspe2(self) -> global___Nspe2Report: ...
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        periodic_report: global___PeriodicReport | None = ...,
        nspe2: global___Nspe2Report | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["nspe2", b"nspe2", "periodic_report", b"periodic_report"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["channel_index", b"channel_index", "nspe2", b"nspe2", "periodic_report", b"periodic_report"]) -> None: ...

global___FullPeriodicReport = FullPeriodicReport

@typing.final
class LockReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    LOCK_FLAGS_FIELD_NUMBER: builtins.int
    LOCK_FREQUENCY_FIELD_NUMBER: builtins.int
    SYMBOL_RATE_FIELD_NUMBER: builtins.int
    DVB_STANDARD_FIELD_NUMBER: builtins.int
    ROLL_OFF_FIELD_NUMBER: builtins.int
    PILOT_FIELD_NUMBER: builtins.int
    SPECTRAL_INVERSION_FIELD_NUMBER: builtins.int
    MODCOD_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    rf_source: builtins.int
    locked: builtins.bool
    lock_flags: builtins.int
    """!< LOCK_DEFINITIF|TUN_LOCKED|PKTDELIN_LOCK|LOCKEDVIT|AGCRF_LOCKED|PLL_LOCK|CAR_LOCK|TIMING_IS_LOCKED"""
    lock_frequency: builtins.int
    symbol_rate: builtins.int
    dvb_standard: global___DVBStandard.ValueType
    roll_off: global___RollOffType.ValueType
    pilot: global___Pilot.ValueType
    spectral_inversion: global___SpectralInversion.ValueType
    modcod: global___Modcod.ValueType
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        rf_source: builtins.int = ...,
        locked: builtins.bool = ...,
        lock_flags: builtins.int = ...,
        lock_frequency: builtins.int = ...,
        symbol_rate: builtins.int = ...,
        dvb_standard: global___DVBStandard.ValueType = ...,
        roll_off: global___RollOffType.ValueType = ...,
        pilot: global___Pilot.ValueType = ...,
        spectral_inversion: global___SpectralInversion.ValueType = ...,
        modcod: global___Modcod.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_index", b"channel_index", "dvb_standard", b"dvb_standard", "lock_flags", b"lock_flags", "lock_frequency", b"lock_frequency", "locked", b"locked", "modcod", b"modcod", "pilot", b"pilot", "rf_source", b"rf_source", "roll_off", b"roll_off", "spectral_inversion", b"spectral_inversion", "symbol_rate", b"symbol_rate"]) -> None: ...

global___LockReport = LockReport

@typing.final
class DataInterface(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ApplicationType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ApplicationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface._ApplicationType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AppType_Transcoder: DataInterface._ApplicationType.ValueType  # 0
        """! the device dumps BBF in UDP packets - TC1x"""
        AppType_Demodulator: DataInterface._ApplicationType.ValueType  # 1
        """! the device has an encapsulator and decaps BBf/GSE and outputs IP packets - VHS500"""

    class ApplicationType(_ApplicationType, metaclass=_ApplicationTypeEnumTypeWrapper): ...
    AppType_Transcoder: DataInterface.ApplicationType.ValueType  # 0
    """! the device dumps BBF in UDP packets - TC1x"""
    AppType_Demodulator: DataInterface.ApplicationType.ValueType  # 1
    """! the device has an encapsulator and decaps BBf/GSE and outputs IP packets - VHS500"""

    @typing.final
    class Detailed(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Type:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._Type.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Type_Undefined: DataInterface.Detailed._Type.ValueType  # 0
            Type_Parallel: DataInterface.Detailed._Type.ValueType  # 1
            Type_Serial: DataInterface.Detailed._Type.ValueType  # 2
            Type_Muxed: DataInterface.Detailed._Type.ValueType  # 3
            """!< TS12_MUXED and TS34_MUXED"""

        class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
        Type_Undefined: DataInterface.Detailed.Type.ValueType  # 0
        Type_Parallel: DataInterface.Detailed.Type.ValueType  # 1
        Type_Serial: DataInterface.Detailed.Type.ValueType  # 2
        Type_Muxed: DataInterface.Detailed.Type.ValueType  # 3
        """!< TS12_MUXED and TS34_MUXED"""

        class _Width:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _WidthEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._Width.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Width_Undefined: DataInterface.Detailed._Width.ValueType  # 0
            Width_Wide: DataInterface.Detailed._Width.ValueType  # 1
            Width_Narrow: DataInterface.Detailed._Width.ValueType  # 2

        class Width(_Width, metaclass=_WidthEnumTypeWrapper): ...
        Width_Undefined: DataInterface.Detailed.Width.ValueType  # 0
        Width_Wide: DataInterface.Detailed.Width.ValueType  # 1
        Width_Narrow: DataInterface.Detailed.Width.ValueType  # 2

        class _Crc:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _CrcEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._Crc.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Crc_Undefined: DataInterface.Detailed._Crc.ValueType  # 0
            Crc_0x47: DataInterface.Detailed._Crc.ValueType  # 1
            Crc_Crc8: DataInterface.Detailed._Crc.ValueType  # 2

        class Crc(_Crc, metaclass=_CrcEnumTypeWrapper): ...
        Crc_Undefined: DataInterface.Detailed.Crc.ValueType  # 0
        Crc_0x47: DataInterface.Detailed.Crc.ValueType  # 1
        Crc_Crc8: DataInterface.Detailed.Crc.ValueType  # 2

        class _Content:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _ContentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._Content.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Content_Undefined: DataInterface.Detailed._Content.ValueType  # 0
            Content_Packet: DataInterface.Detailed._Content.ValueType  # 1
            Content_Frame: DataInterface.Detailed._Content.ValueType  # 2
            Content_Continous: DataInterface.Detailed._Content.ValueType  # 3

        class Content(_Content, metaclass=_ContentEnumTypeWrapper): ...
        Content_Undefined: DataInterface.Detailed.Content.ValueType  # 0
        Content_Packet: DataInterface.Detailed.Content.ValueType  # 1
        Content_Frame: DataInterface.Detailed.Content.ValueType  # 2
        Content_Continous: DataInterface.Detailed.Content.ValueType  # 3

        class _Packetization:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PacketizationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._Packetization.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Packetization_Undefined: DataInterface.Detailed._Packetization.ValueType  # 0
            Packetization_BBF: DataInterface.Detailed._Packetization.ValueType  # 1
            Packetization_Packet: DataInterface.Detailed._Packetization.ValueType  # 2

        class Packetization(_Packetization, metaclass=_PacketizationEnumTypeWrapper): ...
        Packetization_Undefined: DataInterface.Detailed.Packetization.ValueType  # 0
        Packetization_BBF: DataInterface.Detailed.Packetization.ValueType  # 1
        Packetization_Packet: DataInterface.Detailed.Packetization.ValueType  # 2

        class _FooterHeader:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _FooterHeaderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Detailed._FooterHeader.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            FooterHeader_Undefined: DataInterface.Detailed._FooterHeader.ValueType  # 0
            FooterHeader_Footer: DataInterface.Detailed._FooterHeader.ValueType  # 1
            FooterHeader_Header: DataInterface.Detailed._FooterHeader.ValueType  # 2
            FooterHeader_FooterHeader: DataInterface.Detailed._FooterHeader.ValueType  # 3
            FooterHeader_None: DataInterface.Detailed._FooterHeader.ValueType  # 4

        class FooterHeader(_FooterHeader, metaclass=_FooterHeaderEnumTypeWrapper): ...
        FooterHeader_Undefined: DataInterface.Detailed.FooterHeader.ValueType  # 0
        FooterHeader_Footer: DataInterface.Detailed.FooterHeader.ValueType  # 1
        FooterHeader_Header: DataInterface.Detailed.FooterHeader.ValueType  # 2
        FooterHeader_FooterHeader: DataInterface.Detailed.FooterHeader.ValueType  # 3
        FooterHeader_None: DataInterface.Detailed.FooterHeader.ValueType  # 4

        TYPE_FIELD_NUMBER: builtins.int
        WIDTH_FIELD_NUMBER: builtins.int
        CRC_FIELD_NUMBER: builtins.int
        CONTENT_FIELD_NUMBER: builtins.int
        PACKETIZATION_FIELD_NUMBER: builtins.int
        FOOTER_HEADER_FIELD_NUMBER: builtins.int
        CONSTELLATION_FIELD_NUMBER: builtins.int
        type: global___DataInterface.Detailed.Type.ValueType
        width: global___DataInterface.Detailed.Width.ValueType
        crc: global___DataInterface.Detailed.Crc.ValueType
        content: global___DataInterface.Detailed.Content.ValueType
        packetization: global___DataInterface.Detailed.Packetization.ValueType
        footer_header: global___DataInterface.Detailed.FooterHeader.ValueType
        constellation: builtins.bool
        def __init__(
            self,
            *,
            type: global___DataInterface.Detailed.Type.ValueType = ...,
            width: global___DataInterface.Detailed.Width.ValueType = ...,
            crc: global___DataInterface.Detailed.Crc.ValueType = ...,
            content: global___DataInterface.Detailed.Content.ValueType = ...,
            packetization: global___DataInterface.Detailed.Packetization.ValueType = ...,
            footer_header: global___DataInterface.Detailed.FooterHeader.ValueType = ...,
            constellation: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["constellation", b"constellation", "content", b"content", "crc", b"crc", "footer_header", b"footer_header", "packetization", b"packetization", "type", b"type", "width", b"width"]) -> None: ...

    @typing.final
    class Preset(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Type:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DataInterface.Preset._Type.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Type_Undefined: DataInterface.Preset._Type.ValueType  # 0
            Type_NVS: DataInterface.Preset._Type.ValueType  # 1
            Type_Tc1ProX: DataInterface.Preset._Type.ValueType  # 2
            Type_Tc8X: DataInterface.Preset._Type.ValueType  # 3
            Type_TcAnnexM: DataInterface.Preset._Type.ValueType  # 4
            Type_SrxGse: DataInterface.Preset._Type.ValueType  # 5

        class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
        Type_Undefined: DataInterface.Preset.Type.ValueType  # 0
        Type_NVS: DataInterface.Preset.Type.ValueType  # 1
        Type_Tc1ProX: DataInterface.Preset.Type.ValueType  # 2
        Type_Tc8X: DataInterface.Preset.Type.ValueType  # 3
        Type_TcAnnexM: DataInterface.Preset.Type.ValueType  # 4
        Type_SrxGse: DataInterface.Preset.Type.ValueType  # 5

        TYPE_FIELD_NUMBER: builtins.int
        type: global___DataInterface.Preset.Type.ValueType
        def __init__(
            self,
            *,
            type: global___DataInterface.Preset.Type.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["type", b"type"]) -> None: ...

    DETAILED_DEFINITION_FIELD_NUMBER: builtins.int
    PRESET_FIELD_NUMBER: builtins.int
    REG_FILE_FIELD_NUMBER: builtins.int
    APP_TYPE_FIELD_NUMBER: builtins.int
    reg_file: builtins.str
    """!< empty string means no file provided"""
    app_type: global___DataInterface.ApplicationType.ValueType
    @property
    def detailed_definition(self) -> global___DataInterface.Detailed: ...
    @property
    def preset(self) -> global___DataInterface.Preset: ...
    def __init__(
        self,
        *,
        detailed_definition: global___DataInterface.Detailed | None = ...,
        preset: global___DataInterface.Preset | None = ...,
        reg_file: builtins.str = ...,
        app_type: global___DataInterface.ApplicationType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Configuration", b"Configuration", "detailed_definition", b"detailed_definition", "preset", b"preset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Configuration", b"Configuration", "app_type", b"app_type", "detailed_definition", b"detailed_definition", "preset", b"preset", "reg_file", b"reg_file"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["Configuration", b"Configuration"]) -> typing.Literal["detailed_definition", "preset"] | None: ...

global___DataInterface = DataInterface

@typing.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EventType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EventTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Event._EventType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ET_Unknown: Event._EventType.ValueType  # 0
        ET_Unlocked: Event._EventType.ValueType  # 1
        ET_Locked: Event._EventType.ValueType  # 2

    class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...
    ET_Unknown: Event.EventType.ValueType  # 0
    ET_Unlocked: Event.EventType.ValueType  # 1
    ET_Locked: Event.EventType.ValueType  # 2

    EVENT_FIELD_NUMBER: builtins.int
    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    event: global___Event.EventType.ValueType
    channel_index: builtins.int
    def __init__(
        self,
        *,
        event: global___Event.EventType.ValueType = ...,
        channel_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_index", b"channel_index", "event", b"event"]) -> None: ...

global___Event = Event

@typing.final
class PlatformConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FPGA_CTRL_IP_ADDRESS_FIELD_NUMBER: builtins.int
    FPGA_DATA_IP_ADDRESS_FIELD_NUMBER: builtins.int
    fpga_ctrl_ip_address: builtins.str
    fpga_data_ip_address: builtins.str
    def __init__(
        self,
        *,
        fpga_ctrl_ip_address: builtins.str = ...,
        fpga_data_ip_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fpga_ctrl_ip_address", b"fpga_ctrl_ip_address", "fpga_data_ip_address", b"fpga_data_ip_address"]) -> None: ...

global___PlatformConfig = PlatformConfig

@typing.final
class DataInterfaceIpConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FPGA_DATA_IP_ADDRESS_FIELD_NUMBER: builtins.int
    FPGA_DATA_IP_MASK_FIELD_NUMBER: builtins.int
    FPGA_DATA_IP_DEF_GW_FIELD_NUMBER: builtins.int
    FPGA_DATA_MAC_DEF_GW_FIELD_NUMBER: builtins.int
    FPGA_DATA_VLAN_FIELD_NUMBER: builtins.int
    fpga_data_ip_address: builtins.str
    fpga_data_ip_mask: builtins.str
    fpga_data_ip_def_gw: builtins.str
    fpga_data_mac_def_gw: builtins.bytes
    fpga_data_vlan: builtins.int
    def __init__(
        self,
        *,
        fpga_data_ip_address: builtins.str = ...,
        fpga_data_ip_mask: builtins.str = ...,
        fpga_data_ip_def_gw: builtins.str = ...,
        fpga_data_mac_def_gw: builtins.bytes = ...,
        fpga_data_vlan: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fpga_data_ip_address", b"fpga_data_ip_address", "fpga_data_ip_def_gw", b"fpga_data_ip_def_gw", "fpga_data_ip_mask", b"fpga_data_ip_mask", "fpga_data_mac_def_gw", b"fpga_data_mac_def_gw", "fpga_data_vlan", b"fpga_data_vlan"]) -> None: ...

global___DataInterfaceIpConfiguration = DataInterfaceIpConfiguration

@typing.final
class FpgaDebug(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    address: builtins.int
    data: builtins.int
    def __init__(
        self,
        *,
        address: builtins.int = ...,
        data: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "data", b"data"]) -> None: ...

global___FpgaDebug = FpgaDebug

@typing.final
class OxfordDebug(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    RV_FIELD_NUMBER: builtins.int
    address: builtins.int
    data: builtins.int
    rv: builtins.int
    def __init__(
        self,
        *,
        address: builtins.int = ...,
        data: builtins.int = ...,
        rv: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "data", b"data", "rv", b"rv"]) -> None: ...

global___OxfordDebug = OxfordDebug

@typing.final
class BeamHoppingEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    EVENT_DURATION_MS_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    event_duration_ms: builtins.int
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        event_duration_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_index", b"channel_index", "event_duration_ms", b"event_duration_ms"]) -> None: ...

global___BeamHoppingEvent = BeamHoppingEvent

@typing.final
class ChannelInputPair(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    rf_source: builtins.int
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        rf_source: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_index", b"channel_index", "rf_source", b"rf_source"]) -> None: ...

global___ChannelInputPair = ChannelInputPair

@typing.final
class InputPowerLevel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    RF_SOURCE_FIELD_NUMBER: builtins.int
    BAND_POWER_FIELD_NUMBER: builtins.int
    channel_index: builtins.int
    rf_source: builtins.int
    band_power: builtins.float
    def __init__(
        self,
        *,
        channel_index: builtins.int = ...,
        rf_source: builtins.int = ...,
        band_power: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["band_power", b"band_power", "channel_index", b"channel_index", "rf_source", b"rf_source"]) -> None: ...

global___InputPowerLevel = InputPowerLevel

@typing.final
class TodDistribution(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLE_FIELD_NUMBER: builtins.int
    SOURCE_MAC_FIELD_NUMBER: builtins.int
    SOURCE_IP_FIELD_NUMBER: builtins.int
    SOURCE_UDP_PORT_FIELD_NUMBER: builtins.int
    enable: builtins.bool
    source_mac: builtins.str
    source_ip: builtins.str
    source_udp_port: builtins.int
    """string destination_mac = 20;
    string destination_ip = 21;
    uint32 destination_udp_port = 22;
    """
    def __init__(
        self,
        *,
        enable: builtins.bool = ...,
        source_mac: builtins.str = ...,
        source_ip: builtins.str = ...,
        source_udp_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enable", b"enable", "source_ip", b"source_ip", "source_mac", b"source_mac", "source_udp_port", b"source_udp_port"]) -> None: ...

global___TodDistribution = TodDistribution

@typing.final
class RangingConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    UDP_PORT_FIELD_NUMBER: builtins.int
    mac_address: builtins.str
    ip_address: builtins.str
    udp_port: builtins.int
    def __init__(
        self,
        *,
        mac_address: builtins.str = ...,
        ip_address: builtins.str = ...,
        udp_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip_address", b"ip_address", "mac_address", b"mac_address", "udp_port", b"udp_port"]) -> None: ...

global___RangingConfiguration = RangingConfiguration

@typing.final
class Led(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LedColor:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LedColorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Led._LedColor.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Off: Led._LedColor.ValueType  # 0
        Green: Led._LedColor.ValueType  # 1
        Red: Led._LedColor.ValueType  # 2

    class LedColor(_LedColor, metaclass=_LedColorEnumTypeWrapper): ...
    Off: Led.LedColor.ValueType  # 0
    Green: Led.LedColor.ValueType  # 1
    Red: Led.LedColor.ValueType  # 2

    COLOR_FIELD_NUMBER: builtins.int
    color: global___Led.LedColor.ValueType
    def __init__(
        self,
        *,
        color: global___Led.LedColor.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["color", b"color"]) -> None: ...

global___Led = Led
