"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
MDC API"""

import board_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BoardChannel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOARD_INDEX_FIELD_NUMBER: builtins.int
    CHANNEL_INDEX_FIELD_NUMBER: builtins.int
    board_index: builtins.int
    channel_index: builtins.int
    def __init__(
        self,
        *,
        board_index: builtins.int = ...,
        channel_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["board_index", b"board_index", "channel_index", b"channel_index"]) -> None: ...

global___BoardChannel = BoardChannel

@typing.final
class BoardChannelConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOARD_INDEX_FIELD_NUMBER: builtins.int
    CONFIGURATION_FIELD_NUMBER: builtins.int
    UNLOCK_RECONFIG_ATTEMPTS_FIELD_NUMBER: builtins.int
    UNLOCK_RECONFIG_TIMEOUT_FIELD_NUMBER: builtins.int
    board_index: builtins.int
    unlock_reconfig_attempts: builtins.int
    unlock_reconfig_timeout: builtins.int
    @property
    def configuration(self) -> board_pb2.ChannelConfiguration: ...
    def __init__(
        self,
        *,
        board_index: builtins.int = ...,
        configuration: board_pb2.ChannelConfiguration | None = ...,
        unlock_reconfig_attempts: builtins.int = ...,
        unlock_reconfig_timeout: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["configuration", b"configuration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["board_index", b"board_index", "configuration", b"configuration", "unlock_reconfig_attempts", b"unlock_reconfig_attempts", "unlock_reconfig_timeout", b"unlock_reconfig_timeout"]) -> None: ...

global___BoardChannelConfiguration = BoardChannelConfiguration

@typing.final
class Networking(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MANAGEMENT_IP_ADDRESS_FIELD_NUMBER: builtins.int
    MANAGEMENT_IP_SUBNET_MASK_FIELD_NUMBER: builtins.int
    MANAGEMENT_IP_DEFAULT_GATEWAY_FIELD_NUMBER: builtins.int
    management_ip_address: builtins.str
    management_ip_subnet_mask: builtins.str
    management_ip_default_gateway: builtins.str
    def __init__(
        self,
        *,
        management_ip_address: builtins.str = ...,
        management_ip_subnet_mask: builtins.str = ...,
        management_ip_default_gateway: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["management_ip_address", b"management_ip_address", "management_ip_default_gateway", b"management_ip_default_gateway", "management_ip_subnet_mask", b"management_ip_subnet_mask"]) -> None: ...

global___Networking = Networking

@typing.final
class ResetMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Kind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ResetMessage._Kind.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Warm: ResetMessage._Kind.ValueType  # 0
        Cold: ResetMessage._Kind.ValueType  # 1

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper):
        """0 - warm, 1- cold"""

    Warm: ResetMessage.Kind.ValueType  # 0
    Cold: ResetMessage.Kind.ValueType  # 1

    KIND_FIELD_NUMBER: builtins.int
    BOARD_INDEX_FIELD_NUMBER: builtins.int
    kind: global___ResetMessage.Kind.ValueType
    board_index: builtins.int
    def __init__(
        self,
        *,
        kind: global___ResetMessage.Kind.ValueType = ...,
        board_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["board_index", b"board_index", "kind", b"kind"]) -> None: ...

global___ResetMessage = ResetMessage

@typing.final
class Board(google.protobuf.message.Message):
    """General board information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOARD_INDEX_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DEMODULATOR_CHIP_VERSION_FIELD_NUMBER: builtins.int
    DATA_PORT_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    BIT_STATUS_FIELD_NUMBER: builtins.int
    COMMUNICATION_STATUS_FIELD_NUMBER: builtins.int
    CHANNEL_FIELD_NUMBER: builtins.int
    BCA_VERSION_FIELD_NUMBER: builtins.int
    board_index: builtins.int
    status: board_pb2.BoardStatus.ValueType
    demodulator_chip_version: builtins.str
    temperature: builtins.float
    bit_status: board_pb2.BitStatus.ValueType
    communication_status: board_pb2.CommunicationStatus.ValueType
    bca_version: builtins.str
    @property
    def data_port(self) -> board_pb2.DataPort: ...
    @property
    def channel(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[board_pb2.Channel]:
        """Channels"""

    def __init__(
        self,
        *,
        board_index: builtins.int = ...,
        status: board_pb2.BoardStatus.ValueType = ...,
        demodulator_chip_version: builtins.str = ...,
        data_port: board_pb2.DataPort | None = ...,
        temperature: builtins.float = ...,
        bit_status: board_pb2.BitStatus.ValueType = ...,
        communication_status: board_pb2.CommunicationStatus.ValueType = ...,
        channel: collections.abc.Iterable[board_pb2.Channel] | None = ...,
        bca_version: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data_port", b"data_port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bca_version", b"bca_version", "bit_status", b"bit_status", "board_index", b"board_index", "channel", b"channel", "communication_status", b"communication_status", "data_port", b"data_port", "demodulator_chip_version", b"demodulator_chip_version", "status", b"status", "temperature", b"temperature"]) -> None: ...

global___Board = Board
